### ISSUE TITLE
Release SD1.5 Code 

### ISSUE THREAD

**Issue by xugao97** [naver-ai/StyleKeeper#12]
I am particularly interested in the SD1.5 model and its applications.

**Comment by taki0112** [comment]
For the sake of code simplicity, we have only released it for SDXL. There are no plans to release it for SD1.5, but since our methodology is very simple, it can be easily applied using [the following code](https://github.com/naver-ai/Visual-Style-Prompting/blob/1a22e7a2b7106b7093d6c1b557441335a78105ff/pipelines/inverted_ve_pipeline.py#L433).
